name: japanocr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytesseract
  - pdf2image
  - pillow
  - numpy
  - opencv
  - pandas
  - poppler
  - jupyter
  - ipykernel
  - matplotlib
  - pip:
    - pytest